# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ishaan Abhinav
title: UI Engineer
email: ishaanabhinav@gmail.com
# website: ""

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ishaanabhinav
github_username:  ishaanabhinav
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ishaanabhinav
linkedin_username: ishaanabhinav
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Ishaan and I'm a UI Engineer. As well as coding beautiful UI I also have experience making ML and mobile apps.

  I am most skilled in: <mark>Web UI</mark><mark>Django</mark> and <mark>React Native</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-githubx
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CBREX - Global Recruiter Exchange
        link: cbr.exchange
        # link_text: boringcompany.com
        sub_title: UI Engineer
        caption: July 2019 - Present
        sub_title: UI Engineer(Intern)
        caption: April 2018 - July 2019
        quote: >
          The worlds largest sourcing engine for screened talent.
        description: | # this will include new lines to allow paragraphs
          Every company needs UI, app and in some cases ML, well I do it all. Getting UI approval,integrating new gen features is hard but I play my part making sure the whole product looks beautiful and serves its purpose. I work with a small tech team and we enjoy driving the company to try new technologies.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CMR Institute of Technology
        caption: 2015 - 2019
        sub_title: BE Computer Science
        quote: >
          Accredited by NAAC with ‘A’ Grade and affiliated to Visvesvaraya Technological University, Belgaum.
        description: | # this will include new lines to allow paragraphs
          This has just been the best 4 years of my life. I thouroughly enjoyed my time at college and learnt a lot not just about Computers but also life skills.

          I spent a lot of my free time participating in almost a dozen of Hackathons, winning some of them, learning from some of them and extending my network at all of them.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Computers and software engineering some of my other interests and hobbies are:
      - Fitness - Weight Lifting
      - Anime(Luffy will become Pirate King)
      - Reading Blogs(Tech+Life)
      - [Adding Calisthenics to the list soon]

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
