# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Ishaan Abhinav
title: Full Stack Developer
email: ishaanabhinav@gmail.com
# website: ""

# Dark Mode (true/false/never)
darkmode: true

# Social links
twitter_username: ishaanabhinav
github_username:  ishaanabhinav
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: ishaanabhinav
linkedin_username: ishaanabhinav
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: Resume
  icon: fas fa-file-alt
  url: https://ishaanabhinav.github.io/resume/ishaan-resume-compressed.pdf
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Ishaan Abhinav, I’m a full stack web developer with over 3 years experience currently specialising in <mark>ReactNative</mark> and <mark>Django</mark> development. I am currently working for CBREX as a UI Engineer.

  I enjoy making clean and interactive UI that is easy to use whilst also giving users an enjoyable experience. I have worked with a range of languages and frameworks and I am always looking for opportunities to work with something new. The tech that I currently have the most experience working with are: <mark>ES6 Javascript</mark>, <mark>React Native & Redux</mark>, <mark>Django</mark>, <mark>Python</mark>, <mark>Java</mark>, <mark>ML</mark>, <mark>MySQL</mark>, and <mark>git</mark>.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CBREX - Global Recruiter Exchange
        link: cbr.exchange
        # link_text: boringcompany.com
        sub_title: UI Engineer
        caption: April 2018 - Present
        # sub_title: UI Engineer(Intern)
        # caption: April 2018 - July 2019
        quote: >
          The worlds largest sourcing engine for screened talent.
        description: | # this will include new lines to allow paragraphs
          Every company needs UI, app and in some cases ML, well I do it all. Getting UI approval,integrating new gen features is hard but I play my part making sure the whole product looks beautiful and serves its purpose. I work with a small tech team and we enjoy driving the company to try new technologies.
          I worked on <mark>Django</mark>, <mark>React Native</mark>, <mark>Spring Boot</mark>, <mark>Struts</mark> and <mark>HTML,CSS,JQUERY</mark> along the different verticals of company product.

  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: CMR Institute of Technology
        caption: 2015 - 2019
        sub_title: BE Computer Science
        quote: >
          Accredited by NAAC with ‘A’ Grade and affiliated to Visvesvaraya Technological University, Belgaum.
        description: | # this will include new lines to allow paragraphs
          This has just been the best 4 years of my life. I thouroughly enjoyed my time at college and learnt a lot not just about Computers but also life skills.

          I spent a lot of my free time participating in almost a dozen of Hackathons, winning some of them, learning from some of them and extending my network at all of them.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: CBREX Enterprise APP
        sub_title: An Enterprise app for web platform cbr.exchange
        # link_text: Project Website
        quote: >
          A <mark>React Native</mark> app on top of <mark>Expo SDK</mark> with <mark>Spring Boot</mark> on the backend.

      - layout: top-middle
        title: CBREX AI Engine
        sub_title: The engine that is at the core of matching system of cbr.exchange
        # link_text: Project Website
        quote: >
          A <mark>Django</mark> app that uses various <mark>ML Models</mark> for the matching process(visit cbr.exchange for detail).

      - layout: top-middle
        title: COWIN SCRAPPER
        sub_title: Vaccine alert for 18+ in Bengaluru
        # link_text: Project Website
        quote: >
          A <mark>Python</mark> script that consumes the GOI open api and notifies user through a <mark>Telgram Bot</mark>
  
  - title: Courses # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: AI Curriculum Connect
        sub_title: (UK India Tech Partnership - Scholarship)
        sub_title: British High Commission in India 
        link: https://ishaanabhinav.github.io/certificates/ai_certificate_Uk_India.pdf
        link_text: View Cerificate
        quote: >
          A beautiful designed course to help us explore the actual industry use case of ML/AI.
      
  - title: When I'm Not Programming
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in Computers and software engineering some of my other interests and hobbies are:
      - Fitness - Weight Lifting
      - Anime(Luffy will become Pirate King)
      - Reading Blogs(Tech+Life)
      - [Adding Calisthenics to the list soon]

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
